service: cut-optimizer
image: silitix/cut-optimizer

servers:
  web:
    hosts:
      - 51.75.29.25
    options:
      publish:
        - "127.0.0.1:3001:3001"

# SSH user (not root).
ssh:
  user: debian

# No kamal-proxy â€” only accessible from localhost on the host.
proxy: false

registry:
  server: registry.hub.docker.com
  username: silitix
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PORT: "3001"
