service: cut-optimizer
image: your-dockerhub-username/cut-optimizer

servers:
  web:
    hosts:
      - 51.75.29.25

proxy:
  host: 51.75.29.25
  ssl: false
  app_port: 3001

registry:
  username: silitix
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PORT: "3001"
