service: cut-optimizer
image: silitix/cut-optimizer

servers:
  web:
    hosts:
      - 51.75.29.25
    # No kamal-proxy â€” only accessible from localhost on the host.
    proxy: false
    options:
      network: shared
      network-alias: cut-optimizer

# SSH user (not root).
ssh:
  user: debian

registry:
  server: registry.hub.docker.com
  username: silitix
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PORT: "3001"
